name: Pembaruan EPG Otomatis

on:
  schedule:
    # Menjadwalkan skrip berjalan setiap hari pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: # Memunculkan tombol agar kita bisa menjalankannya manual

jobs:
  build:
    runs-on: ubuntu-latest
steps:
          - name: Mengambil File Repositori
            uses: actions/checkout@v3

          - name: Menyiapkan Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Menginstal Library yang Dibutuhkan # <-- TAMBAHKAN BAGIAN INI
            run: pip install -r requirements.txt

          - name: Menjalankan Skrip Python
            run: python generate_epg.py

          - name: Menyimpan epg.xml Kembali ke GitHub
            # ... (kode git config seperti sebelumnya) ...
